# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ramon/sem5/SK2/projekt/serwer/kalambury_server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ramon/sem5/SK2/projekt/serwer/kalambury_server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ramon/sem5/SK2/projekt/serwer/kalambury_server/CMakeFiles /home/ramon/sem5/SK2/projekt/serwer/kalambury_server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ramon/sem5/SK2/projekt/serwer/kalambury_server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kalambury_server

# Build rule for target.
kalambury_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kalambury_server
.PHONY : kalambury_server

# fast build rule for target.
kalambury_server/fast:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/build
.PHONY : kalambury_server/fast

ConnectionInputHandler.o: ConnectionInputHandler.cpp.o

.PHONY : ConnectionInputHandler.o

# target to build an object file
ConnectionInputHandler.cpp.o:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/ConnectionInputHandler.cpp.o
.PHONY : ConnectionInputHandler.cpp.o

ConnectionInputHandler.i: ConnectionInputHandler.cpp.i

.PHONY : ConnectionInputHandler.i

# target to preprocess a source file
ConnectionInputHandler.cpp.i:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/ConnectionInputHandler.cpp.i
.PHONY : ConnectionInputHandler.cpp.i

ConnectionInputHandler.s: ConnectionInputHandler.cpp.s

.PHONY : ConnectionInputHandler.s

# target to generate assembly for a file
ConnectionInputHandler.cpp.s:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/ConnectionInputHandler.cpp.s
.PHONY : ConnectionInputHandler.cpp.s

DataStorage.o: DataStorage.cpp.o

.PHONY : DataStorage.o

# target to build an object file
DataStorage.cpp.o:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/DataStorage.cpp.o
.PHONY : DataStorage.cpp.o

DataStorage.i: DataStorage.cpp.i

.PHONY : DataStorage.i

# target to preprocess a source file
DataStorage.cpp.i:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/DataStorage.cpp.i
.PHONY : DataStorage.cpp.i

DataStorage.s: DataStorage.cpp.s

.PHONY : DataStorage.s

# target to generate assembly for a file
DataStorage.cpp.s:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/DataStorage.cpp.s
.PHONY : DataStorage.cpp.s

PackageStucture.o: PackageStucture.cpp.o

.PHONY : PackageStucture.o

# target to build an object file
PackageStucture.cpp.o:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/PackageStucture.cpp.o
.PHONY : PackageStucture.cpp.o

PackageStucture.i: PackageStucture.cpp.i

.PHONY : PackageStucture.i

# target to preprocess a source file
PackageStucture.cpp.i:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/PackageStucture.cpp.i
.PHONY : PackageStucture.cpp.i

PackageStucture.s: PackageStucture.cpp.s

.PHONY : PackageStucture.s

# target to generate assembly for a file
PackageStucture.cpp.s:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/PackageStucture.cpp.s
.PHONY : PackageStucture.cpp.s

Server.o: Server.cpp.o

.PHONY : Server.o

# target to build an object file
Server.cpp.o:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/Server.cpp.o
.PHONY : Server.cpp.o

Server.i: Server.cpp.i

.PHONY : Server.i

# target to preprocess a source file
Server.cpp.i:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/Server.cpp.i
.PHONY : Server.cpp.i

Server.s: Server.cpp.s

.PHONY : Server.s

# target to generate assembly for a file
Server.cpp.s:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/Server.cpp.s
.PHONY : Server.cpp.s

User.o: User.cpp.o

.PHONY : User.o

# target to build an object file
User.cpp.o:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/User.cpp.o
.PHONY : User.cpp.o

User.i: User.cpp.i

.PHONY : User.i

# target to preprocess a source file
User.cpp.i:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/User.cpp.i
.PHONY : User.cpp.i

User.s: User.cpp.s

.PHONY : User.s

# target to generate assembly for a file
User.cpp.s:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/User.cpp.s
.PHONY : User.cpp.s

WebMessageParser.o: WebMessageParser.cpp.o

.PHONY : WebMessageParser.o

# target to build an object file
WebMessageParser.cpp.o:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/WebMessageParser.cpp.o
.PHONY : WebMessageParser.cpp.o

WebMessageParser.i: WebMessageParser.cpp.i

.PHONY : WebMessageParser.i

# target to preprocess a source file
WebMessageParser.cpp.i:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/WebMessageParser.cpp.i
.PHONY : WebMessageParser.cpp.i

WebMessageParser.s: WebMessageParser.cpp.s

.PHONY : WebMessageParser.s

# target to generate assembly for a file
WebMessageParser.cpp.s:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/WebMessageParser.cpp.s
.PHONY : WebMessageParser.cpp.s

WebMessagesStorage.o: WebMessagesStorage.cpp.o

.PHONY : WebMessagesStorage.o

# target to build an object file
WebMessagesStorage.cpp.o:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/WebMessagesStorage.cpp.o
.PHONY : WebMessagesStorage.cpp.o

WebMessagesStorage.i: WebMessagesStorage.cpp.i

.PHONY : WebMessagesStorage.i

# target to preprocess a source file
WebMessagesStorage.cpp.i:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/WebMessagesStorage.cpp.i
.PHONY : WebMessagesStorage.cpp.i

WebMessagesStorage.s: WebMessagesStorage.cpp.s

.PHONY : WebMessagesStorage.s

# target to generate assembly for a file
WebMessagesStorage.cpp.s:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/WebMessagesStorage.cpp.s
.PHONY : WebMessagesStorage.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/kalambury_server.dir/build.make CMakeFiles/kalambury_server.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... kalambury_server"
	@echo "... edit_cache"
	@echo "... ConnectionInputHandler.o"
	@echo "... ConnectionInputHandler.i"
	@echo "... ConnectionInputHandler.s"
	@echo "... DataStorage.o"
	@echo "... DataStorage.i"
	@echo "... DataStorage.s"
	@echo "... PackageStucture.o"
	@echo "... PackageStucture.i"
	@echo "... PackageStucture.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... User.o"
	@echo "... User.i"
	@echo "... User.s"
	@echo "... WebMessageParser.o"
	@echo "... WebMessageParser.i"
	@echo "... WebMessageParser.s"
	@echo "... WebMessagesStorage.o"
	@echo "... WebMessagesStorage.i"
	@echo "... WebMessagesStorage.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

